env:
  global:
    - NODE_ENV=test

language: node_js

node_js:
  - "stable"

before_script:
  - npm install
script:
  - npm run test

after_success:
  - npm run coverage

cache:
  directories:
    - "node_modules"
  yarn: true

notifications:
  email: false
sudo: false

services:
  - postgresql
