name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test:ci
      env:
        CI_DB_URL: postgres://diuufquoindnkx:2c396b2ea7d796317d79965a9bbf76095e08feefca7a981a3614157a360793da@ec2-35-168-54-239.compute-1.amazonaws.com:5432/d3jnp07h8bsjmj
        TOKEN_SECRET: secret
        FRONTEND_URL: http://localhost:3000/api/v1
